### ISSUE TITLE
module.js:340

### ISSUE THREAD

**Issue by CrossfireSoftwarez** [bemehiser/Tether#1]
used your "tether-master"
compiled, and received the following:

pi@raspberrypi:~/tether $ sudo linux/run.sh
/home/pi/tether
Starting Tether...

module.js:340
    throw err;
          ^
Error: Cannot find module 'chainsaw'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/pi/tether/node-tuntap/node_modules/binary/index.js:1:78)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)

**Comment by bemehiser** [comment]
I've never tried to compile on a Raspberry Pi. What compiler version are you using, and what generation of Pi do you have?

**Comment by bemehiser** [comment]
I just reproduced this when attempting to compile in Ubuntu 18.04 using GCC 7.3.0

For a temporary workaround, I would recommend trying to compile with an older compiler (gcc6).

**Comment by CrossfireSoftwarez** [comment]
UPDATE:

so uninstalled all GCC, then installed GCC-6
recompiled, and same error. never did put in new GCC, so older as opposed to newer may/may not change things
BUT!!!:
i installed NPM (node package manager):
sudo apt-get install npm

then told it to install chainsaw:
npm install chainsaw

then new error, complaining about the adb exec

copied the apt installed adb to the tether folder replacing the adb there and then all worked!

then for my use, i routed my tun to eth0, set it to auto run the run.sh on boot, plug in phone, run tether on phone, boot PI, and i have internet feeding my wireless router

Thank you @bemehiser for the work you did to the tether files. hope this helps others

**Comment by bemehiser** [comment]
Awesome. Thanks for the solution @CrossfireSoftwarez. I'll look into this to see if it works on new Ubuntu systems. If it does, I'll see about hacking out the ancient nodejs, and replacing it with new packages.

**Comment by Jeff4Success** [comment]
Not sure if this is still open, or I should open a new thread, but I've got this error now, running on Manjaro

```
Starting Tether...
* daemon not running; starting now at tcp:5037
* daemon started successfully
Opening tun device.
Opening tun device: /dev/net/tun
Opening tun device: null
unable to open tun/tap device.
TypeError: os.setupTun is not a function
    at new tun (/home/jeff/appdev/Tether/node-tuntap/tuntap.js:111:6)
    at createTun (/home/jeff/appdev/Tether/node-tuntap/tether.js:42:15)
    at Object.<anonymous> (/home/jeff/appdev/Tether/node-tuntap/tether.js:242:1)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
```
Let me know if you need more info. Thanks!

**Comment by FossPrime** [comment]
Had the same issue on Raspbian with a Raspberry Pi Zero ArmV6

**Comment by kevinaj** [comment]
@Jeff4Success Are you using the version of node built from this source? See #4 for why you have to.
